// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/weblfe/flyfire/app/account/service/internal/biz"
	"github.com/weblfe/flyfire/app/account/service/internal/conf"
	"github.com/weblfe/flyfire/app/account/service/internal/data"
	"github.com/weblfe/flyfire/app/account/service/internal/server"
	"github.com/weblfe/flyfire/app/account/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(arg []string, registry *conf.Registry, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	registrar, err := data.NewRegistrar(registry)
	if err != nil {
		return nil, nil, err
	}
	v := server.NewEndpoints(arg)
	engineInterface, err := data.NewDbClient(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, engineInterface, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger)
	accountUseCase := biz.NewAccountUseCase(accountRepo, logger)
	accountService := service.NewAccountService(accountUseCase)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	httpServer := server.NewHTTPServer(confServer, accountService, logger)
	app := newApp(registrar, v, logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
